### PR TITLE
Identify users when they connect wallet.

### PR DESCRIPTION
**Pull request by rootedbox**

### CODE REVIEW

**Review by kkennis — CHANGES_REQUESTED** [review]
@rootedbox this PR does not build:

```
/Users/kevin/p/il-loss-charts/packages/client/src/hooks/use-wallet.tsx
TypeScript error in /Users/kevin/p/il-loss-charts/packages/client/src/hooks/use-wallet.tsx(262,22):
Property 'identify' does not exist on type 'MixpanelWrapper'.  TS2339

    260 |             mixpanel.people?.set({ distinct_id: account, wallet: account });
    261 |
  > 262 |             mixpanel.identify(account);
        |                      ^
    263 |             mixpanel.track('wallet:connected', mixpanelData);
    264 |         } catch (e) {
    265 |             console.error(`Metrics error on wallet.`);
```

Can you update `util/mixpanel.js` to handle this new mixpanel call? you can use `mixpanel.people` as a template

**Comment by rootedbox** [comment]
@kkennis I didn't know this but the function I was trying to use isn't available in the node.js version of the library. I have instead change how I make a call to the people set function.

I've also added the code to load the Mixpanel javascript better on the front end.

**Comment by kkennis** [comment]
We don't need to load mixpanel in `index.html`, it is already part of the NPM bundle. Were you running into some issue that was derived by not importing it there?

Otherwise code looks good and builds.

**Comment by rootedbox** [comment]
image

yah we need the regular Mixpanel library for the front end calls we need to make. 

@kkennis

**Comment by kkennis** [comment]
Gotcha, looks good then. Thanks @rootedbox

**Review by kkennis — APPROVED** [review]

**Pull request merged**
