### PR TITLE
add joinCommunity button, update title and heading in pair page

### PR DESCRIPTION
**Pull request by ddguru777**

### CODE REVIEW

**Comment by kkennis** [comment]
Hey Adam, we usually do not use the `dev` branch for merge targets since it can change at anytime - it's only for deployment. Do you want to target this PR at `main`?

**Comment by ddguru777** [comment]
@kkennis - this is good to go.

**Review by kkennis — APPROVED** [review]
Yep looks good!

**Comment by ddguru777** [comment]
> Yep looks good!
@kkennis this one seems to be merged on your end. I don't have permission to handle this.

**Review by rootedbox — APPROVED** [review]
LGTM

**Pull request merged**
